apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
  namespace: flask-app
  labels:
    app: flask-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
    protocol: TCP
    name: http
  - port: 9100
    targetPort: 5000
    protocol: TCP
    name: metrics
  selector:
    app: flask-app
