apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: grafana
  labels:
    app: grafana
spec:
  type: NodePort  # For local access; use LoadBalancer for cloud environments
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: web
      nodePort: 32000  # Choose an available port within the NodePort range (30000-32767)
  selector:
    app: grafana
