apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
  namespace: elk
data:
  filebeat.yml: |-
    filebeat.autodiscover:
      providers:
        - type: kubernetes
          hints.enabled: true
          templates:
            - condition:
                equals:
                  kubernetes.namespace: "flask-app"
              config:
                - type: container
                  paths:
                    - /var/log/containers/*${data.kubernetes.container.id}.log
                  exclude_lines: ["^\\s+[\\-`('.|_]"]

    processors:
      - add_cloud_metadata: ~
      - add_host_metadata: ~
      - add_kubernetes_metadata:
          in_cluster: true
          matchers:
          - logs_path:
              path: "/var/log/containers/"

    output.elasticsearch:
      hosts: ['http://elasticsearch.elk.svc.cluster.local:9200']